version: '3'
services:
  elasticsearch:
    image: elasticsearch:7.17.20
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - test_data:/usr/share/elasticsearch/data/
      - ./elk-config/elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    environment:
      node.name: elasticsearch
      ES_JAVA_OPTS: -Xms512m -Xmx512m
      ELASTIC_PASSWORD: password
      discovery.type: single-node
      network.bind_host: 0.0.0.0
    networks:
      - elk
networks:
  elk:
    driver: bridge
volumes:
  test_data: